-- MySQL Script generated by MySQL Workbench
-- 07/16/18 20:51:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Equipo` (
  `Equi_ID` INT NOT NULL,
  `Equi_Nombre_Pais` VARCHAR(45) NULL,
  `Equi_NumeroDeGoles` INT NULL,
  `Equi_Escudo` VARCHAR(45) NULL,
  PRIMARY KEY (`Equi_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jugador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Jugador` (
  `Jugu_ID` INT NOT NULL,
  `Jugu_Nombre` VARCHAR(45) NULL,
  `Jugu_Apellidos` VARCHAR(45) NULL,
  `Equipo_Equi_ID` INT NOT NULL,
  `Jugu_NumCamisa` VARCHAR(45) NULL,
  `Jugu_Posicion` VARCHAR(45) NULL,
  PRIMARY KEY (`Jugu_ID`),
  CONSTRAINT `fk_Jugador_Equipo1`
    FOREIGN KEY (`Equipo_Equi_ID`)
    REFERENCES `mydb`.`Equipo` (`Equi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `Pais_ID` INT NOT NULL,
  `Pais_Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Pais_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ciudad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `Ciud_ID` INT NOT NULL,
  `Ciud_Nombre` VARCHAR(45) NULL,
  `Pais_Pais_ID` INT NOT NULL,
  PRIMARY KEY (`Ciud_ID`, `Pais_Pais_ID`),
  CONSTRAINT `fk_Ciudad_Pais1`
    FOREIGN KEY (`Pais_Pais_ID`)
    REFERENCES `mydb`.`Pais` (`Pais_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estadio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Estadio` (
  `Esta_ID` INT NOT NULL,
  `Esta_Nombre` VARCHAR(45) NULL,
  `Esta_Capacidad` VARCHAR(45) NULL,
  `Ciudad_Ciud_ID` INT NOT NULL,
  `Ciudad_Pais_Pais_ID` INT NOT NULL,
  PRIMARY KEY (`Esta_ID`, `Ciudad_Ciud_ID`, `Ciudad_Pais_Pais_ID`),
  CONSTRAINT `fk_Estadio_Ciudad1`
    FOREIGN KEY (`Ciudad_Ciud_ID` , `Ciudad_Pais_Pais_ID`)
    REFERENCES `mydb`.`Ciudad` (`Ciud_ID` , `Pais_Pais_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `Even_id` INT NOT NULL,
  `Even_Nombre` VARCHAR(45) NULL,
  `Even_Minuto` VARCHAR(45) NULL,
  `Jugador_Jugu_ID` INT NOT NULL,
  PRIMARY KEY (`Even_id`, `Jugador_Jugu_ID`),
  CONSTRAINT `fk_Eventos_Jugador1`
    FOREIGN KEY (`Jugador_Jugu_ID`)
    REFERENCES `mydb`.`Jugador` (`Jugu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Partidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Partidos` (
  `Part_ID` INT NOT NULL,
  `Part_Fecha` VARCHAR(45) NULL,
  `Part_Hora` VARCHAR(45) NULL,
  `Part_Resultado` VARCHAR(45) NULL,
  `Estadio_Esta_ID` INT NOT NULL,
  `Estadio_Ciudad_Ciud_ID` INT NOT NULL,
  `Estadio_Ciudad_Pais_Pais_ID` INT NOT NULL,
  `Eventos_Even_id` INT NOT NULL,
  `Eventos_Jugador_Jugu_ID` INT NOT NULL,
  PRIMARY KEY (`Part_ID`, `Estadio_Esta_ID`, `Estadio_Ciudad_Ciud_ID`, `Estadio_Ciudad_Pais_Pais_ID`, `Eventos_Even_id`, `Eventos_Jugador_Jugu_ID`),
  CONSTRAINT `fk_Partidos_Estadio1`
    FOREIGN KEY (`Estadio_Esta_ID` , `Estadio_Ciudad_Ciud_ID` , `Estadio_Ciudad_Pais_Pais_ID`)
    REFERENCES `mydb`.`Estadio` (`Esta_ID` , `Ciudad_Ciud_ID` , `Ciudad_Pais_Pais_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_Eventos1`
    FOREIGN KEY (`Eventos_Even_id` , `Eventos_Jugador_Jugu_ID`)
    REFERENCES `mydb`.`Eventos` (`Even_id` , `Jugador_Jugu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Arbitro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Arbitro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Arbitro` (
  `Arbi_ID` INT NOT NULL,
  `Arbi_Nombre` VARCHAR(45) NULL,
  `Arbi_Pais` VARCHAR(45) NULL,
  `Arbi_Apellido` VARCHAR(45) NULL,
  `Arbi_Funcion` VARCHAR(45) NULL,
  `Tipo_Arbitro_Tipo_ID` INT NOT NULL,
  PRIMARY KEY (`Arbi_ID`, `Tipo_Arbitro_Tipo_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Partidos_has_Arbitros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partidos_has_Arbitros` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Partidos_has_Arbitros` (
  `Partidos_ID_partidos` INT NOT NULL,
  `Arbitros_id_Arbitros` INT NOT NULL,
  PRIMARY KEY (`Partidos_ID_partidos`, `Arbitros_id_Arbitros`),
  CONSTRAINT `fk_Partidos_has_Arbitros_Partidos1`
    FOREIGN KEY (`Partidos_ID_partidos`)
    REFERENCES `mydb`.`Partidos` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_has_Arbitros_Arbitros1`
    FOREIGN KEY (`Arbitros_id_Arbitros`)
    REFERENCES `mydb`.`Arbitro` (`Arbi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Equipo_has_Partidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipo_has_Partidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Equipo_has_Partidos` (
  `Partidos_Part_ID` INT NOT NULL,
  `Equipo_Equi_ID` INT NOT NULL,
  PRIMARY KEY (`Partidos_Part_ID`, `Equipo_Equi_ID`),
  CONSTRAINT `fk_Equipo_has_Partidos_Equipo1`
    FOREIGN KEY (`Equipo_Equi_ID`)
    REFERENCES `mydb`.`Equipo` (`Equi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_has_Partidos_Partidos1`
    FOREIGN KEY (`Partidos_Part_ID`)
    REFERENCES `mydb`.`Partidos` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Partidos_has_Arbitro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partidos_has_Arbitro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Partidos_has_Arbitro` (
  `Partidos_Part_ID` INT NOT NULL,
  `Arbitro_Arbi_ID` INT NOT NULL,
  PRIMARY KEY (`Partidos_Part_ID`, `Arbitro_Arbi_ID`),
  CONSTRAINT `fk_Partidos_has_Arbitro_Partidos1`
    FOREIGN KEY (`Partidos_Part_ID`)
    REFERENCES `mydb`.`Partidos` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_has_Arbitro_Arbitro1`
    FOREIGN KEY (`Arbitro_Arbi_ID`)
    REFERENCES `mydb`.`Arbitro` (`Arbi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Club` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `Club_ID` INT NOT NULL,
  `Club_Nombre` VARCHAR(45) NULL,
  `Club_Logo` VARCHAR(45) NULL,
  `Ciudad_Ciud_ID` INT NOT NULL,
  `Ciudad_Pais_Pais_ID` INT NOT NULL,
  PRIMARY KEY (`Club_ID`, `Ciudad_Ciud_ID`, `Ciudad_Pais_Pais_ID`),
  CONSTRAINT `fk_Club_Ciudad1`
    FOREIGN KEY (`Ciudad_Ciud_ID` , `Ciudad_Pais_Pais_ID`)
    REFERENCES `mydb`.`Ciudad` (`Ciud_ID` , `Pais_Pais_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Jugador_has_Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jugador_has_Club` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Jugador_has_Club` (
  `Jugador_Jugu_ID` INT NOT NULL,
  `Club_Club_ID` INT NOT NULL,
  PRIMARY KEY (`Jugador_Jugu_ID`, `Club_Club_ID`),
  CONSTRAINT `fk_Jugador_has_Club_Jugador1`
    FOREIGN KEY (`Jugador_Jugu_ID`)
    REFERENCES `mydb`.`Jugador` (`Jugu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_has_Club_Club1`
    FOREIGN KEY (`Club_Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`AntiDopaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AntiDopaje` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`AntiDopaje` (
  `Anti_ID` INT NOT NULL,
  `Anti_Fecha` DATETIME NULL,
  `Anti_Resultado` VARCHAR(6) NULL,
  `Anti_Lugar` VARCHAR(45) NULL,
  `Jugador_Jugu_ID` INT NOT NULL,
  PRIMARY KEY (`Anti_ID`),
  CONSTRAINT `fk_AntiDopaje_Jugador1`
    FOREIGN KEY (`Jugador_Jugu_ID`)
    REFERENCES `mydb`.`Jugador` (`Jugu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `Hote_id` INT NOT NULL,
  `Hote_Nombre` VARCHAR(45) NULL,
  `Hote_HabitacionNum` VARCHAR(45) NULL,
  `Hote_Direccion` VARCHAR(45) NULL,
  `Hote_Tel` VARCHAR(45) NULL,
  PRIMARY KEY (`Hote_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `Rese_FechaInto` DATETIME NULL,
  `Rese_FechaSali` DATETIME NULL,
  `Rese_ID` INT NOT NULL,
  `Rese_NumHabitacio` INT NULL,
  `Equipo_Equi_ID` INT NOT NULL,
  `Hotel_Hote_id` INT NOT NULL,
  PRIMARY KEY (`Rese_ID`, `Equipo_Equi_ID`, `Hotel_Hote_id`),
  CONSTRAINT `fk_Reserva_Equipo1`
    FOREIGN KEY (`Equipo_Equi_ID`)
    REFERENCES `mydb`.`Equipo` (`Equi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Hotel1`
    FOREIGN KEY (`Hotel_Hote_id`)
    REFERENCES `mydb`.`Hotel` (`Hote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
