-- MySQL Script generated by MySQL Workbench
-- 07/26/18 19:24:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MinDefensa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MinDefensa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MinDefensa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MinDefensa` ;

-- -----------------------------------------------------
-- Table `MinDefensa`.`RolSoldado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`RolSoldado` (
  `rols_id` INT NOT NULL AUTO_INCREMENT,
  `rols_nombre` VARCHAR(45) NULL,
  `CuerpSoldado_cuer_id` INT NOT NULL,
  PRIMARY KEY (`rols_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_Ciudad` (
  `ciud_id` INT NULL,
  `ciud_Nombre` VARCHAR(45) NULL,
  `ciud_registradopor` VARCHAR(20) NULL,
  `ciud_fechareg` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_Compañia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_Compañia` (
  `comp_id` INT NULL,
  `comp_actividad` VARCHAR(45) NULL,
  `comp_registradopor` VARCHAR(20) NULL,
  `comp_fechareg` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_cuartel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_cuartel` (
  `cuar_id` INT NULL,
  `cuar_nombre` VARCHAR(45) NULL,
  `cuar_Direccion` VARCHAR(45) NULL,
  `cuar_registradopor` VARCHAR(20) NULL,
  `cuar_fechareg` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_AccionServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_AccionServicio` (
  `accs_id` INT NULL,
  `accs_descripcion` VARCHAR(45) NULL,
  `accs_fechaINI` DATETIME NULL,
  `accs_fechaFIN` DATETIME NULL,
  `accs_registradopor` VARCHAR(20) NULL,
  `accs_fechareg` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_Soldado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_Soldado` (
  `sold_id` INT NULL,
  `sold_nombre` VARCHAR(45) NULL,
  `sold_apellido` VARCHAR(45) NULL,
  `sold_promocion` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_CuerpSoldado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_CuerpSoldado` (
  `Cuer_id` INT NULL,
  `cuer_tipo` VARCHAR(45) NULL,
  `cuer_registradopor` VARCHAR(20) NULL,
  `cuer_fechareg` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinDefensa`.`Aud_RolSoldado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Aud_RolSoldado` (
  `rols_id` INT NULL,
  `rols_nombre` VARCHAR(45) NULL,
  `rols_registradopor` VARCHAR(20) NULL,
  `rols_fechareg` DATETIME NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
