-- MySQL Script generated by MySQL Workbench
-- 07/26/18 19:19:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MinDefensa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MinDefensa` ;

-- -----------------------------------------------------
-- Schema MinDefensa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MinDefensa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `MinDefensa` ;

-- -----------------------------------------------------
-- Table `MinDefensa`.`RolSoldado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`RolSoldado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`RolSoldado` (
  `rols_id` INT NOT NULL AUTO_INCREMENT,
  `rols_nombre` VARCHAR(45) NULL,
  `rols_registradopor` VARCHAR(20) NULL,
  `rols_fechareg` DATETIME NULL,
  PRIMARY KEY (`rols_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`CuerpSoldado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`CuerpSoldado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`CuerpSoldado` (
  `cuer_id` INT NOT NULL AUTO_INCREMENT,
  `cuer_tipo` VARCHAR(45) NULL,
  `cuer_registradopor` VARCHAR(20) NULL,
  `cuer_fechareg` DATETIME NULL,
  `RolSoldado_rols_id` INT NOT NULL,
  PRIMARY KEY (`cuer_id`, `RolSoldado_rols_id`),
  INDEX `fk_CuerpSoldado_RolSoldado1_idx` (`RolSoldado_rols_id` ASC),
  CONSTRAINT `fk_CuerpSoldado_RolSoldado1`
    FOREIGN KEY (`RolSoldado_rols_id`)
    REFERENCES `MinDefensa`.`RolSoldado` (`rols_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`Ciudad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Ciudad` (
  `ciud_id` INT NOT NULL AUTO_INCREMENT,
  `ciud_Nombre` VARCHAR(45) NULL,
  `ciud_registradopor` VARCHAR(20) NULL,
  `ciud_fechareg` DATETIME NULL,
  PRIMARY KEY (`ciud_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`Cuartel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`Cuartel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Cuartel` (
  `cuar_id` INT NOT NULL AUTO_INCREMENT,
  `cuar_nombre` VARCHAR(45) NULL,
  `cuar_Direccion` VARCHAR(45) NULL,
  `cuar_registradopor` VARCHAR(20) NULL,
  `cuar_fechareg` DATETIME NULL,
  `Ciudad_ciud_id` INT NOT NULL,
  PRIMARY KEY (`cuar_id`),
  INDEX `fk_Cuartel_Ciudad1_idx` (`Ciudad_ciud_id` ASC),
  CONSTRAINT `fk_Cuartel_Ciudad1`
    FOREIGN KEY (`Ciudad_ciud_id`)
    REFERENCES `MinDefensa`.`Ciudad` (`ciud_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`Compania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`Compania` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Compania` (
  `comp_id` INT NOT NULL AUTO_INCREMENT,
  `comp_actividad` VARCHAR(45) NULL,
  `comp_registradopor` VARCHAR(20) NULL,
  `comp_fechareg` DATETIME NULL,
  PRIMARY KEY (`comp_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`Soldado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`Soldado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`Soldado` (
  `sold_id` INT NOT NULL AUTO_INCREMENT,
  `sold_nombre` VARCHAR(45) NULL,
  `sold_apellido` VARCHAR(45) NULL,
  `sold_promocion` DATETIME NULL,
  `Cuartel_cuar_id` INT NOT NULL,
  `CuerpSoldado_cuer_id` INT NOT NULL,
  `Cuartel_cuar_id1` INT NOT NULL,
  `Compania_comp_id` INT NOT NULL,
  PRIMARY KEY (`sold_id`),
  INDEX `fk_Soldado_CuerpSoldado1_idx` (`CuerpSoldado_cuer_id` ASC),
  INDEX `fk_Soldado_Cuartel1_idx` (`Cuartel_cuar_id1` ASC),
  INDEX `fk_Soldado_Compania1_idx` (`Compania_comp_id` ASC),
  CONSTRAINT `fk_Soldado_CuerpSoldado1`
    FOREIGN KEY (`CuerpSoldado_cuer_id`)
    REFERENCES `MinDefensa`.`CuerpSoldado` (`cuer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldado_Cuartel1`
    FOREIGN KEY (`Cuartel_cuar_id1`)
    REFERENCES `MinDefensa`.`Cuartel` (`cuar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldado_Compania1`
    FOREIGN KEY (`Compania_comp_id`)
    REFERENCES `MinDefensa`.`Compania` (`comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`AccionServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`AccionServicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`AccionServicio` (
  `accs_id` INT NOT NULL AUTO_INCREMENT,
  `accs_descripcion` VARCHAR(60) NULL,
  `accs_fechaINI` DATETIME NULL,
  `accs_fechaFIN` DATETIME NULL,
  `accs_registradopor` VARCHAR(20) NULL,
  `accs_fechareg` DATETIME NULL,
  `Soldado_sold_id` INT NOT NULL,
  PRIMARY KEY (`accs_id`),
  INDEX `fk_AccionServicio_Soldado1_idx` (`Soldado_sold_id` ASC),
  CONSTRAINT `fk_AccionServicio_Soldado1`
    FOREIGN KEY (`Soldado_sold_id`)
    REFERENCES `MinDefensa`.`Soldado` (`sold_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MinDefensa`.`RolSoldado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinDefensa`.`RolSoldado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MinDefensa`.`RolSoldado` (
  `rols_id` INT NOT NULL AUTO_INCREMENT,
  `rols_nombre` VARCHAR(45) NULL,
  `rols_registradopor` VARCHAR(20) NULL,
  `rols_fechareg` DATETIME NULL,
  PRIMARY KEY (`rols_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
